### ISSUE TITLE
Dupes, Saves and others

### ISSUE THREAD

**Issue by 60percentCaffeine** [gigte/glua-menu#2]
Can you make the temporary version of Saves, Demos and other pages that not ported yet, by loading default GMOD HTML version?

**Comment by GIGte** [comment]
I'm not sure how this would work. For this I would need to take some parts of the HTML menu, and then somehow integrate them into this one. The HTML menu is a single system, if that is even possible, I would have to understand how to load a certain page, and how to communicate with it in Lua.

I don't think there would be any sense in spending time on adding HTML back. Isn't it better to just write Lua code?

You can always use "menu_swap", if you need the missing features.

**Comment by GIGte** [comment]
And by the way, there are only "Saves", "Demos" and Addon browsing (though you can do the same via Steam Workshop site) missing.
